import { useMemo, useState } from "react";
import { Clock3, FileText, History, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { adminAccessAction, isAdminAccessDenied } from "@/lib/admin/adminAccess";
import { formatBillingDate } from "@/lib/billing/manualPayments";
import type { AdminAccessHistoryRow, AdminHistoryResponse } from "@/lib/billing/types";

type HistoryFilter = "all" | "access" | "billing";
function actionLabel(action: string): string { return action.replaceAll("_", " ").toLowerCase().replace(/(^|\s)\S/g, (letter) => letter.toUpperCase()); }
function HistoryRow({ row }: { row: AdminAccessHistoryRow }) { return <li className={`admin-history-item is-${row.kind}`}><div className="admin-history-marker">{row.kind === "billing" ? <FileText className="h-3.5 w-3.5" /> : <ShieldCheck className="h-3.5 w-3.5" />}</div><div className="admin-history-body"><div className="admin-history-top"><div><strong>{actionLabel(row.action)}</strong>{row.target_user_email && <span>{row.target_user_email}</span>}</div><time>{formatBillingDate(row.occurred_at)}</time></div><p>{row.note || row.summary || "No note recorded."}</p><div className="admin-history-meta"><span>Actor: {row.actor_label}</span>{row.related_payment_id && <span>Payment: {row.related_payment_id}</span>}{row.related_subscription_id && <span>Subscription: {row.related_subscription_id}</span>}{row.metadata_text && <span>{row.metadata_text}</span>}</div></div></li>; }

export function AdminAccessHistory({ history, loading, onRefresh, onDenied }: { history: AdminHistoryResponse | null; loading: boolean; onRefresh: () => void; onDenied: () => void }) {
  const [filter, setFilter] = useState<HistoryFilter>("all"); const [search, setSearch] = useState(""); const [error, setError] = useState("");
  const rows = useMemo(() => { const all = filter === "access" ? history?.access_events || [] : filter === "billing" ? history?.billing_events || [] : [...(history?.access_events || []), ...(history?.billing_events || [])]; const query = search.trim().toLowerCase(); return all.filter((row) => !query || `${row.action} ${row.target_user_email} ${row.note} ${row.summary}`.toLowerCase().includes(query)).sort((a, b) => Date.parse(b.occurred_at) - Date.parse(a.occurred_at)); }, [history, filter, search]);
  const refresh = async () => { setError(""); try { await adminAccessAction({ action: "history" }); onRefresh(); } catch (requestError) { console.error("Could not refresh access history", requestError); if (isAdminAccessDenied(requestError)) onDenied(); else setError("Access history could not be refreshed."); } };
  return <section className="admin-history"><div className="admin-section-heading"><div><p className="admin-section-kicker">Private timeline</p><h3>Access and billing history</h3><p>Lifecycle changes and billing audit events stay separate, with receipt payloads and credentials excluded from this summary.</p></div><Button type="button" variant="outline" className="admin-header-button" onClick={() => void refresh()} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</Button></div><div className="admin-history-toolbar"><div className="admin-history-tabs" role="tablist" aria-label="History type"><button type="button" role="tab" aria-selected={filter === "all"} className={filter === "all" ? "is-active" : ""} onClick={() => setFilter("all")}>All events</button><button type="button" role="tab" aria-selected={filter === "access"} className={filter === "access" ? "is-active" : ""} onClick={() => setFilter("access")}>Access lifecycle</button><button type="button" role="tab" aria-selected={filter === "billing"} className={filter === "billing" ? "is-active" : ""} onClick={() => setFilter("billing")}>Billing audit</button></div><label className="admin-search-field"><Search className="h-4 w-4" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Find an account or action" aria-label="Search history" /></label></div>{error && <div className="admin-feedback is-error" role="alert">{error}</div>}{loading && !history ? <div className="admin-loading"><RefreshCw className="h-4 w-4 animate-spin" />Loading private history…</div> : rows.length ? <ol className="admin-history-list">{rows.map((row) => <HistoryRow key={`${row.kind}-${row.id}`} row={row} />)}</ol> : <div className="admin-empty"><History className="h-5 w-5" /><p>No events match this view.</p></div>}<div className="admin-history-footnote"><Clock3 className="h-4 w-4" /><span>Times use the server-recorded event timestamp. Account timing labels distinguish account-created metadata from first authenticated activity.</span></div></section>;
}
